services:
    olveneer.slot_extension:
        class: Olveneer\TwigComponentsBundle\Twig\SlotExtension
        arguments: ['@olveneer.component_renderer']
        tags: ['twig.extension']

    olveneer.component_store:
        class: Olveneer\TwigComponentsBundle\Service\ComponentStore
        arguments: []

    olveneer.config_store:
        class: Olveneer\TwigComponentsBundle\Service\ConfigStore
        arguments: ['/components', 'component', 'access']

    olveneer.component_renderer:
        class: Olveneer\TwigComponentsBundle\Service\ComponentRenderer
        arguments: ['@olveneer.component_store', '@twig', '@olveneer.config_store']
        lazy: true

    Olveneer\TwigComponentsBundle\Service\ComponentStore:       '@olveneer.component_store'
    Olveneer\TwigComponentsBundle\Service\ComponentRenderer:    '@olveneer.component_renderer'
    Olveneer\TwigComponentsBundle\Twig\SlotExtension:           '@olveneer.slot_extension'
    Olveneer\TwigComponentsBundle\Service\ConfigStore:          '@olveneer.config_store'
