services:
    olveneer.component_extension:
        class: Olveneer\TwigComponentsBundle\Twig\TwigComponentExtension
        arguments: ['@olveneer.component_kernel', '', '']
        tags: ['twig.extension']

    olveneer.slot_extension:
        class: Olveneer\TwigComponentsBundle\Twig\SlotExtension
        arguments: ['@olveneer.component_kernel']
        tags: ['twig.extension']

    olveneer.component_store:
        class: Olveneer\TwigComponentsBundle\Service\TwigComponentStore
        arguments: []

    olveneer.component_kernel:
        class: Olveneer\TwigComponentsBundle\Service\TwigComponentKernel
        arguments: ['@olveneer.component_store', '@twig', '']

    Olveneer\TwigComponentsBundle\Twig\TwigComponentExtension: '@olveneer.component_extension'
    Olveneer\TwigComponentsBundle\Service\TwigComponentStore: '@olveneer.component_store'
    Olveneer\TwigComponentsBundle\Service\TwigComponentKernel: '@olveneer.component_kernel'
    Olveneer\TwigComponentsBundle\Twig\SlotExtension:         '@olveneer.slot_extension'
