services:
    olveneer.component_loader:
        class: Olveneer\TwigComponentsBundle\Resources\src\TwigComponentLoader
        public: false
        arguments: ['@Olveneer\TwigComponentsBundle\Resources\src\TwigComponentKernel']
        tags:
            - { name: twig.extension }

    olveneer.component_store:
        class: Olveneer\TwigComponentsBundle\Resources\src\TwigComponentStore

    Olveneer\TwigComponentsBundle\Resources\src\TwigComponentKernel:
        arguments: ['@olveneer.component_store', '@twig', '']
